# systemctl list-unit-files | grep service.*enabled |sed 's/.service.*enabled//g' | awk '{print "\""$1"\","}'

def test_serv(host):
    for spec in (
"accounts-daemon",
"activemq",
"apparmor",
"atd",
"auditd",
"autovt@",
"blk-availability",
"console-setup",
"cron",
"dbus-fi.w1.wpa_supplicant1",
"dbus-org.freedesktop.resolve1",
"dbus-org.freedesktop.thermald",
"dns-clean",
"fail2ban",
"getty@",
"irqbalance",
"kafka",
"keyboard-setup",
"lvm2-monitor",
"mysql",
"networkd-dispatcher",
"networking",
"ntp",
"ondemand",
"postfix",
"postgresql",
"pppd-dns",
"resolvconf",
"rsync",
"rsyslog",
"setvtrgb",
"ssh",
"sshd",
"syslog",
"sysstat",
"systemd-fsck-root-runtime",
"systemd-resolved",
"systemd-timesyncd",
"thermald",
"ufw",
"unattended-upgrades",
"ureadahead",
"wildfly",
"wpa_supplicant",
"zabbix-agent",
"zookeeper",
    ):  
        service= host.service(spec)
        assert service.is_enabled


