# systemctl list-unit-files | grep service.*enabled |sed 's/.service.*enabled//g' | awk '{print "\""$1"\","}'
# systemctl list-units --type=service --state=active
# systemctl list-units --type=service --state=active|grep \.service |sed  's/.service//g' | awk '{print "\""$1"\","}'

def test_serv_active(host):
    for spec in (
"accounts-daemon",
"acpid",
"apache2",
"apparmor",
"apport",
"atd",
"auditd",
"bind9",
"console-setup",
"cron",
"dbus",
"fail2ban",
"getty@tty1",
"grub-common",
"haveged",
"ifup@ens160",
"irqbalance",
"iscsid",
"keyboard-setup",
"kmod-static-nodes",
"lvm2-lvmetad",
"lvm2-monitor",
"lxcfs",
"lxd-containers",
"mdadm",
"mongod",
"mysql",
"networking",
"nginx",
"ntp",
"ondemand",
"open-iscsi",
"open-vm-tools",
"orthphoto",
"polkitd",
"postfix",
"postgresql",
"postgresql@9.5-main", "psad",
"rc-local",
"resolvconf",
"rsyslog",
"setvtrgb",
"snapd.apparmor",
"snapd.seeded",
"ssh",
"sysstat",
"systemd-fsck@dev-disk-by\x2duuid-17fa6111\x2d6acd\x2d48b0\x2d96ca\x2db8064f2270dd",
"systemd-fsck@dev-sdb1",
"systemd-fsck@dev-sdc1",
"systemd-journal-flush",
"systemd-journald",
"systemd-logind",
"systemd-modules-load",
"systemd-random-seed",
"systemd-remount-fs",
"systemd-sysctl",
"systemd-tmpfiles-setup-dev",
"systemd-tmpfiles-setup",
"systemd-udev-trigger",
"systemd-udevd",
"systemd-update-utmp",
"systemd-user-sessions",
"ufw",
"unattended-upgrades",
"user@1003",
"vgauth",
"zabbix-agent",
    ):  
        service= host.service(spec)
        assert service.is_running


